/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: SWCook API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.swcook.front.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property steps
 * @property nextPage
 * @property previousPage
 * @property total
 */
@JsonClass(generateAdapter = true)
data class GetStepsResponse(
    @Json(name = "steps") @field:Json(name = "steps") var steps: List<Step>,
    @Json(name = "next_page") @field:Json(name = "next_page") var nextPage: Int? = null,
    @Json(name = "previous_page") @field:Json(name = "previous_page") var previousPage: Int? = null,
    @Json(name = "total") @field:Json(name = "total") var total: Long? = null
)
