/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: SWCook API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.example.swcook.front.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property description
 * @property type
 */
@JsonClass(generateAdapter = true)
data class PostIngredientRequest(
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null
)
